# Generated by Django 4.1.5 on 2023-01-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgtoken',
            name='chat_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
